site_name: Epic Heresy
theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: amber
      toggle:
        icon: material/toggle-switch
    - scheme: slate
      primary: blue grey
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
  custom_dir: overrides
  logo: assets/EH_Logo.png
  favicon: assets/EH_Favicon.ico
  features:  
    - header.autohide
    - navigation.indexes
    - navigation.tabs
    - navigation.top
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/tooltip_special_rules.md
        - includes/tooltip_weapon_traits.md
validation:
  absolute_links: ignore
nav:
  - Quick Start Guide:
      - Quick Start Guide: quick_start_guide/index.md
      - Reference Sheet: quick_start_guide/reference_sheet.md
  - Legions Imperialis Rules:
      - The Rules: legions_imperialis_rules/the_rules.md
      - Core Principles: legions_imperialis_rules/core_principles.md
      - Playing the Game: legions_imperialis_rules/playing_the_game.md
      - Terrain: legions_imperialis_rules/terrain.md
      - Titans: legions_imperialis_rules/titans.md
      - Weapon Traits: legions_imperialis_rules/weapon_traits.md
      - Special Rules: legions_imperialis_rules/special_rules.md
      - Fighting a Battle: legions_imperialis_rules/fighting_a_battle.md
      - Missions: legions_imperialis_rules/missions.md
      - Secondary Objectives: legions_imperialis_rules/secondary_objectives.md
      - Mustering an Army: legions_imperialis_rules/mustering_an_army.md
      - Spearhead Assault Battles: legions_imperialis_rules/spearhead_assault_battles.md
      - Spearhead Assault Missions: legions_imperialis_rules/spearhead_assault_missions.md
      - FAQ: legions_imperialis_rules/faq.md
  - Legions Imperialis Campaigns:
      - Campaigns Overview: legions_imperialis_campaigns/index.md
      - Warfront Campaign: legions_imperialis_campaigns/warfront_campaign.md
      - Conquest Campaigns: legions_imperialis_campaigns/conquest_campaigns.md
      - "Conquest Campaign: The Second Battle for Nyrcon City": legions_imperialis_campaigns/conquest_campaign_the_second_battle_for_nyrcon_city.md
      - Breakthrough Campaigns: legions_imperialis_campaigns/breakthrough_campaigns.md
      - "Breakthrough Campaign: The Northern Desolation": legions_imperialis_campaigns/breakthrough_campaign_the_northern_desolation.md
      - Escalation Campaigns: legions_imperialis_campaigns/escalation_campaigns.md
      - Grand Clash: legions_imperialis_campaigns/grand_clash.md
      - "Grand Clash: The Fall of Magma City": legions_imperialis_campaigns/grand_clash_the_fall_of_magma_city.md
      - Fog of War: legions_imperialis_campaigns/fog_of_war.md
      - Battle Honours: legions_imperialis_campaigns/battle_honours.md
      - Campaign Expansions: legions_imperialis_campaigns/campaign_expansions.md
      - Flashpoint Missions: legions_imperialis_campaigns/flashpoint_missions.md
      - Additional Missions: legions_imperialis_campaigns/additional_missions.md
      - Historical Missions: legions_imperialis_campaigns/historical_missions.md
  - Titandeath:
      - Overview: titandeath/index.md
      - Battle Sequence: titandeath/titandeath_battle_sequence.md
      - Missions: titandeath/titandeath_missions.md
      - Secondary Objectives: titandeath/titandeath_secondary_objectives.md
  - Factions:
      - Factions: factions/index.md
      - Legiones Astartes:
          - Legiones Astartes: factions/legiones_astartes/index.md
          - Formations: factions/legiones_astartes/formations.md
          - Detachments: factions/legiones_astartes/detachments.md
          - Special Rules: factions/legiones_astartes/special_rules.md
      - Solar Auxilia:
          - Solar Auxilia: factions/solar_auxilia/index.md
          - Formations: factions/solar_auxilia/formations.md
          - Detachments: factions/solar_auxilia/detachments.md
      - Mechanicum Taghmata:
          - Mechanicum Taghmata: factions/mechanicum_taghmata/index.md
          - Formations: factions/mechanicum_taghmata/formations.md
          - Detachments: factions/mechanicum_taghmata/detachments.md
      - Dark Mechanicum:
          - Dark Mechanicum: factions/dark_mechanicum/index.md
          - Formations: factions/dark_mechanicum/formations.md
          - Detachments: factions/dark_mechanicum/detachments.md
      - Collegia Titanica:
          - Collegia Titanica: factions/collegia_titanica/index.md
          - Formations: factions/collegia_titanica/formations.md
          - Detachments: factions/collegia_titanica/detachments.md
      - Knight Households:
          - Knight Households: factions/knight_households/index.md
          - Formations: factions/knight_households/formations.md
          - Detachments: factions/knight_households/detachments.md
  - Formations:
      - Iconic Formations: 
          - Iconic Formations: formations/iconic_formations/index.md
          - Legiones Astartes: formations/iconic_formations/legiones_astartes.md
          - Solar Auxilia: formations/iconic_formations/solar_auxilia.md
          - Mechanicum Taghmata: formations/iconic_formations/mechanicum_taghmata.md
          - Dark Mechanicum: formations/iconic_formations/dark_mechanicum.md
          - Collegia Titanica: formations/iconic_formations/collegia_titanica.md
      - Bonded Cybernetica Support Formations:
          - Bonded Cybernetica Support Formations: formations/bonded_cybernetica/index.md
          - Legiones Astartes: formations/bonded_cybernetica/legiones_astartes.md
          - Solar Auxilia: formations/bonded_cybernetica/solar_auxilia.md
          - Mechanicum Taghmata: formations/bonded_cybernetica/mechanicum_taghmata.md
          - Dark Mechanicum: formations/bonded_cybernetica/dark_mechanicum.md
          - Collegia Titanica: formations/bonded_cybernetica/collegia_titanica.md
          - Knight Households: formations/bonded_cybernetica/knight_households.md
  - Reference Section:
      - Detachment Reference: reference/detachment_reference.md
      - Weapon Profiles: reference/weapon_profiles.md
